import React from 'react'

export const AddTag = (draft, content) => {
    if (!HasTag(draft, content)) {
        draft.标签.push({ content: content, enabled: true });
    }
}

export const HasTag = (draft, content) => {
    let has = false;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content === content) {
            has = true;
            break;
        }
    }
    return has
}

export const RemoveTag = (draft, content) => {
    let idx = -1;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content === content) {
            idx = i;
            break;
        }
    }
    if (idx >= 0) {
        draft.标签.splice(idx, 1);
    }
}

export const ExchangeTag = (draft, content1, content2) => {
    var idx1 = -1, idx2 = -1;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content === content1) {
            idx1 = i;
        }
        else if (draft.标签[i].content === content2) {
            idx2 = i;
        }
        if (idx1 >= 0 && idx2 >= 0) {
            break;
        }
    }
    if (idx1 >= 0 && idx2 >= 0) {
        let temp = draft.标签[idx1]
        draft.标签[idx1] = draft.标签[idx2]
        draft.标签[idx2] = temp
    }
}

export const HasVarTag = (draft, content) => {
    let has = false;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content.length > content.length + 1) {
            if (draft.标签[i].content.substr(0, content.length) === content) {
                has = true;
                break;
            }
        }
    }
    return has
}

export const AddVarTag = (draft, content, value) => {
    let has = false;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content.length > content.length + 1) {
            if (draft.标签[i].content.substr(0, content.length) === content) {
                has = true;
                draft.标签[i].content = content + ":" + value
                draft.标签[i].enabled = true;
                break;
            }
        }
    }
    if (!has) {
        draft.标签.push({ content: content + ":" + value, enabled: true })
    }
}

export const GetVarTagValue = (draft, content) => {
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content.length > content.length + 1) {
            if (draft.标签[i].content.substr(0, content.length) === content) {
                return draft.标签[i].content.substr(content.length + 1)
            }
        }
    }
    return ""
}

export const RemoveVarTag = (draft, content) => {
    let idx = -1;
    for (let i = 0; i < draft.标签.length; i++) {
        if (draft.标签[i].content.length > content.length + 1) {
            if (draft.标签[i].content.substr(0, content.length) === content) {
                idx = i;
                break;
            }
        }
    }
    if (idx >= 0) {
        draft.标签.splice(idx, 1);
    }
}

export const GetQuery = (draft) => {
    var queries = ""
    switch (draft.当前页面) {
        case "草图": {
            queries += "industrial design sketch"
            break
        }
        case "草模": {
            queries += "industrial design sketch white model"
            break
        }
        case "效果图": {
            queries += "real"
            break
        }
        default: {
            return ""
        }
    }
    var lastQueries = []
    for (let i = 0; i < draft.标签.length; i++) {

        if (draft.标签[i].content.indexOf(':') === -1) {
            let query = draft.表达式[draft.标签[i].content]
            if (query !== undefined) {
                if (query.substr(0, 1) === ":" || query.substr(0, 1) === "-") lastQueries.push(query)
                else queries += " " + query + ","
            }
        } else {
            let query = draft.表达式[draft.标签[i].content.substr(0, draft.标签[i].content.indexOf(':'))]
            if (query !== undefined) {
                if (query.substr(0, 1) === ":" || query.substr(0, 1) === "-") lastQueries.push(query + " " + draft.标签[i].content.substr(draft.标签[i].content.indexOf(':') + 1))
                else queries += " " + query + " " + draft.标签[i].content.substr(draft.标签[i].content.indexOf(':') + 1) + ","
            }
        }
    }

    for (let i = 0; i < lastQueries.length; i++) {
        queries += " " + lastQueries[i]
    }
    return queries
}

export const Model = () => {
    return {
        "禁用优化": false,
        "处理中": false,
        "上传图片": "",
        "拖放位置": "",
        "弹出框": "",
        "当前子页面": "主子页面",
        "痕迹底框": false,
        "收藏底框": false,
        "收藏": {
            "产品排列/整齐/草图1": [false, <img src={process.env.PUBLIC_URL + "/textures/0.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
            "产品排列/整齐/草图2": [false, <img src={process.env.PUBLIC_URL + "/textures/1.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
            "产品排列/整齐/草图3": [false, <img src={process.env.PUBLIC_URL + "/textures/2.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
            "产品排列/整齐/草图4": [false, <img src={process.env.PUBLIC_URL + "/textures/3.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
            "产品排列/整齐/草图5": [false, <img src={process.env.PUBLIC_URL + "/textures/4.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
            "产品排列/整齐/草图6": [false, <img src={process.env.PUBLIC_URL + "/textures/5.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />],
        },
        "痕迹": { "生成1": "2023/5/1 20:00:00", "生成2": "2023/5/1 20:00:00" },
        "种子编号": "",
        "混沌值": "",
        "可选页面": ["草图", "草模", "效果图"],
        "当前页面": "草图",
        "标签": [],
        "图像比例": "",
        "图片质量": "",
        "景深": "",
        "风格化": "",
        "色调": "",
        "版本": "",
        "邀请码": "邀请码",

        "草图": {
            "作图方式": "",
            "草图背景": {
                "白色背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/6.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "白色背景" },
                "黑色背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/7.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "黑色背景" },
            },

            "草图风格": {
                "简约风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/简约风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "简约风格" },
                "经典风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/经典风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "经典风格" },
                "复古风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/复古风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "复古风格" },
                "索尼风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/索尼风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "索尼风格" },
                "高科技风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/高科技风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "高科技风格" },
                "时尚风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/时尚风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "时尚风格" },
                "像素画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/像素画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "像素画风格" },
                "未来主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/未来主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "未来主义风格" },
                "极简主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/极简主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "极简主义风格" },
                "粗犷主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/粗犷主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "粗犷主义风格" },
                "建构主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/建构主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "建构主义风格" },
                "旷野之息风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/旷野之息风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "旷野之息风格" },
                "星际战甲风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/星际战甲风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "星际战甲风格" },
                "达芬奇风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/达芬奇风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "达芬奇风格" },
                "漫画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/漫画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "漫画风格" },
                "点彩派风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/点彩派风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "点彩派风格" },
                "克劳德莫奈风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/克劳德莫奈风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "克劳德莫奈风格" },
                "绗缝艺术风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/绗缝艺术风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "绗缝艺术风格" },
                "局部解剖风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/局部解剖风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "局部解剖风格" },
                "彩墨纸本风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/彩墨纸本风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "彩墨纸本风格" },
                "涂鸦风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/涂鸦风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "涂鸦风格" },
                "伏尼契手稿风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/伏尼契手稿风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "伏尼契手稿风格" },
                "东方山水画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/东方山水画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "东方山水画风格" },
                "浮世绘风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/浮世绘风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "浮世绘风格" },
                "日本漫画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/日本漫画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "日本漫画风格" },
                "童话故事书插图风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/童话故事书插图风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "童话故事书插图风格" },
                "梦工厂动画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/梦工厂动画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "梦工厂动画风格" },
                "梦工厂影业风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/梦工厂影业风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "梦工厂影业风格" },
                "皮克斯风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/皮克斯风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "皮克斯风格" },
                "日本海报风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/日本海报风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "日本海报风格" },
                "90年代电视游戏风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/90年代电视游戏风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "90年代电视游戏风格" },
                "法国艺术风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/草图风格/法国艺术风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "法国艺术风格" },
            },
            "草图排列": {
                "单个": { icon: <img src={process.env.PUBLIC_URL + "/textures/16.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "单个" },
                "多个随机": { icon: <img src={process.env.PUBLIC_URL + "/textures/17.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "多个随机" },
                "多个整齐": { icon: <img src={process.env.PUBLIC_URL + "/textures/18.jpg"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "多个整齐" },
            }
        },
        "概念效果图": {
            "视角": "",
            "产品材质": {
                "棉材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/棉材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "棉材质" },
                "涤纶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/涤纶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "涤纶材质" },
                "丝绸材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/丝绸材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "丝绸材质" },
                "羊毛材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/羊毛材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "羊毛材质" },
                "腈纶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/腈纶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "腈纶材质" },
                "麻材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/麻材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "麻材质" },
                "竹纤维材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/竹纤维材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "竹纤维材质" },
                "尼龙材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/尼龙材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "尼龙材质" },
                "聚酯材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/聚酯材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "聚酯材质" },
                "蕾丝材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/蕾丝材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "蕾丝材质" },
                "棉麻材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/棉麻材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "棉麻材质" },
                "氨纶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/氨纶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "氨纶材质" },
                "混纺材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/混纺材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "混纺材质" },
                "皮革材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/皮革材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "皮革材质" },
                "仿皮材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/仿皮材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "仿皮材质" },
                "胶合板材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/胶合板材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "胶合板材质" },
                "人造板材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/人造板材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "人造板材质" },
                "复合地板材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/复合地板材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "复合地板材质" },
                "实木地板材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/实木地板材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "实木地板材质" },
                "陶瓷材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/陶瓷材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "陶瓷材质" },
                "马赛克材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/马赛克材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "马赛克材质" },
                "玻璃材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/玻璃材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "玻璃材质" },
                "金属材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/金属材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "金属材质" },
                "铁材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铁材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铁材质" },
                "钢材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/钢材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "钢材质" },
                "铝材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铝材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铝材质" },
                "铜材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铜材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铜材质" },
                "铅材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铅材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铅材质" },
                "镀锌钢材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀锌钢材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀锌钢材质" },
                "不锈钢材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/不锈钢材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "不锈钢材质" },
                "铬材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铬材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铬材质" },
                "镍材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镍材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镍材质" },
                "纸张材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/纸张材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "纸张材质" },
                "塑料材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/塑料材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "塑料材质" },
                "PVC材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/PVC材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "PVC材质" },
                "PE材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/PE材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "PE材质" },
                "PP材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/PP材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "PP材质" },
                "ABS材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/ABS材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "ABS材质" },
                "PC材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/PC材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "PC材质" },
                "乳胶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/乳胶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "乳胶材质" },
                "硅胶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/硅胶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "硅胶材质" },
                "橡胶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/橡胶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "橡胶材质" },
                "泡沫材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/泡沫材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "泡沫材质" },
                "海绵材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/海绵材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "海绵材质" },
                "木头材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/木头材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "木头材质" },
                "胶木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/胶木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "胶木材质" },
                "橡木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/橡木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "橡木材质" },
                "桦木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/桦木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "桦木材质" },
                "枫木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/枫木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "枫木材质" },
                "樱桃木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/樱桃木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "樱桃木材质" },
                "竹子材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/竹子材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "竹子材质" },
                "水泥材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/水泥材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "水泥材质" },
                "石膏材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/石膏材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "石膏材质" },
                "砖材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/砖材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "砖材质" },
                "石头材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/石头材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "石头材质" },
                "大理石材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/大理石材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "大理石材质" },
                "花岗岩材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/花岗岩材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "花岗岩材质" },
                "玄武岩材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/玄武岩材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "玄武岩材质" },
                "石英材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/石英材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "石英材质" },
                "玻璃纤维材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/玻璃纤维材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "玻璃纤维材质" },
                "碳纤维材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/碳纤维材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "碳纤维材质" },
                "石棉材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/石棉材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "石棉材质" },
                "矿棉材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/矿棉材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "矿棉材质" },
                "草编材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/草编材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "草编材质" },
                "藤编材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/藤编材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "藤编材质" },
                "竹编材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/竹编材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "竹编材质" },
                "棉线材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/棉线材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "棉线材质" },
                "麻线材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/麻线材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "麻线材质" },
                "编织物材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/编织物材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "编织物材质" },
                "针织物材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/针织物材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "针织物材质" },
                "珍珠棉材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/珍珠棉材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "珍珠棉材质" },
                "三明治布材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/三明治布材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "三明治布材质" },
                "软陶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/软陶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "软陶材质" },
                "聚氨酯材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/聚氨酯材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "聚氨酯材质" },
                "羊绒材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/羊绒材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "羊绒材质" },
                "麂皮材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/麂皮材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "麂皮材质" },
                "亚克力材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/亚克力材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "亚克力材质" },
                "镁合金材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镁合金材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镁合金材质" },
                "钛合金材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/钛合金材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "钛合金材质" },
                "锌合金材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/锌合金材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "锌合金材质" },
                "硅酸盐材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/硅酸盐材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "硅酸盐材质" },
                "酒瓶绿材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/酒瓶绿材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "酒瓶绿材质" },
                "硝基棉材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/硝基棉材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "硝基棉材质" },
                "硫化纤维材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/硫化纤维材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "硫化纤维材质" },
                "醋酸纤维材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/醋酸纤维材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "醋酸纤维材质" },
                "玉石材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/玉石材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "玉石材质" },
                "珊瑚材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/珊瑚材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "珊瑚材质" },
                "贝壳材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/贝壳材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "贝壳材质" },
                "水晶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/水晶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "水晶材质" },
                "琉璃材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/琉璃材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "琉璃材质" },
                "镁板材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镁板材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镁板材质" },
                "铁皮材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/铁皮材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "铁皮材质" },
                "棕榈叶材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/棕榈叶材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "棕榈叶材质" },
                "软木材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/软木材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "软木材质" },
                "泡材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/泡材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "泡材质" },
                "麦穗材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/麦穗材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "麦穗材质" },
                "麻布材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/麻布材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "麻布材质" },
                "羊毛毡材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/羊毛毡材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "羊毛毡材质" },
                "皮革带材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/皮革带材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "皮革带材质" },
                "棉纱材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/棉纱材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "棉纱材质" },
                "油布材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/油布材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "油布材质" },
                "镀金属材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀金属材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀金属材质" },
                "镀银材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀银材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀银材质" },
                "镀铜材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀铜材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀铜材质" },
                "镀铝材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀铝材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀铝材质" },
                "镀锌材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀锌材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀锌材质" },
                "镀锡材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀锡材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀锡材质" },
                "镀镍材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀镍材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀镍材质" },
                "镀铬材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/镀铬材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镀铬材质" },
                "砂纸材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/砂纸材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "砂纸材质" },
                "砂布材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/砂布材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "砂布材质" },
                "砂轮材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/砂轮材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "砂轮材质" },
                "纱线材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/纱线材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "纱线材质" },
                "粘合剂材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/粘合剂材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "粘合剂材质" },
                "隔热材料材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/隔热材料材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "隔热材料材质" },
                "网布材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/网布材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "网布材质" },
                "蜡烛材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/蜡烛材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "蜡烛材质" },
                "泥土材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/泥土材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "泥土材质" },
                "沙子材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/沙子材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "沙子材质" },
                "泥炭材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/泥炭材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "泥炭材质" },
                "花岗岩碎石材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/花岗岩碎石材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "花岗岩碎石材质" },
                "卵石材质": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品材质/卵石材质.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "卵石材质" },
            },
            "产品风格": {
                "包豪斯风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/包豪斯风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "包豪斯风格" },
                "简约风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/简约风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "简约风格" },
                "复古风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/复古风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "复古风格" },
                "像素画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/像素画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "像素画风格" },
                "未来主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/未来主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "未来主义风格" },
                "极简主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/极简主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "极简主义风格" },
                "粗犷主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/粗犷主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "粗犷主义风格" },
                "建构主义风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/建构主义风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "建构主义风格" },
                "旷野之息风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/旷野之息风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "旷野之息风格" },
                "星际战甲风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/星际战甲风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "星际战甲风格" },
                "达芬奇风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/达芬奇风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "达芬奇风格" },
                "漫画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/漫画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "漫画风格" },
                "点彩派风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/点彩派风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "点彩派风格" },
                "克劳德莫奈风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/克劳德莫奈风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "克劳德莫奈风格" },
                "绗缝艺术风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/绗缝艺术风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "绗缝艺术风格" },
                "彩墨纸本风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/彩墨纸本风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "彩墨纸本风格" },
                "涂鸦风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/涂鸦风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "涂鸦风格" },
                "伏尼契手稿风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/伏尼契手稿风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "伏尼契手稿风格" },
                "东方山水画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/东方山水画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "东方山水画风格" },
                "浮世绘风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/浮世绘风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "浮世绘风格" },
                "日本漫画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/日本漫画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "日本漫画风格" },
                "童话故事书插图风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/童话故事书插图风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "童话故事书插图风格" },
                "梦工厂动画风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/梦工厂动画风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "梦工厂动画风格" },
                "梦工厂影业风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/梦工厂影业风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "梦工厂影业风格" },
                "皮克斯风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/皮克斯风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "皮克斯风格" },
                "时尚风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/时尚风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "时尚风格" },
                "日本海报风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/日本海报风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "日本海报风格" },
                "90年代电视游戏风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/90年代电视游戏风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "90年代电视游戏风格" },
                "法国艺术风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/法国艺术风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "法国艺术风格" },
                "现代风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/现代风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "现代风格" },
                "经典风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/经典风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "经典风格" },
                "优雅风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/优雅风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "优雅风格" },
                "奢华风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/奢华风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "奢华风格" },
                "实用风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/实用风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "实用风格" },
                "工业风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/工业风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "工业风格" },
                "创意风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/创意风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "创意风格" },
                "温馨风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/温馨风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "温馨风格" },
                "高科技风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/高科技风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "高科技风格" },
                "环保风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/环保风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "环保风格" },
                "艺术风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/艺术风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "艺术风格" },
                "手工风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/手工风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "手工风格" },
                "乡村风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/乡村风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "乡村风格" },
                "北欧风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/北欧风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "北欧风格" },
                "极简风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/极简风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "极简风格" },
                "立体风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/立体风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "立体风格" },
                "拉丁风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/拉丁风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "拉丁风格" },
                "迷你风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/迷你风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "迷你风格" },
                "动感风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/动感风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "动感风格" },
                "美式风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/美式风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "美式风格" },
                "异国风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/异国风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "异国风格" },
                "舒适风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/舒适风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "舒适风格" },
                "轻奢风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/轻奢风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "轻奢风格" },
                "阳光风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/阳光风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "阳光风格" },
                "干净风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/干净风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "干净风格" },
                "趣味风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/趣味风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "趣味风格" },
                "自然风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/自然风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "自然风格" },
                "新奇风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/新奇风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "新奇风格" },
                "优质风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/优质风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "优质风格" },
                "抽象风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/抽象风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "抽象风格" },
                "家庭风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/家庭风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "家庭风格" },
                "独特风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/独特风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "独特风格" },
                "可爱风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可爱风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可爱风格" },
                "清新风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/清新风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "清新风格" },
                "精致风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/精致风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "精致风格" },
                "粗犷风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/粗犷风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "粗犷风格" },
                "老式风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/老式风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "老式风格" },
                "古典风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/古典风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "古典风格" },
                "活泼风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/活泼风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "活泼风格" },
                "金属风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/金属风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "金属风格" },
                "幽默风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/幽默风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "幽默风格" },
                "贴心风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/贴心风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "贴心风格" },
                "可定制风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可定制风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可定制风格" },
                "明亮风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/明亮风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "明亮风格" },
                "弧形风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/弧形风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "弧形风格" },
                "软性风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/软性风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "软性风格" },
                "强烈风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/强烈风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "强烈风格" },
                "可塑风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可塑风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可塑风格" },
                "美观风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/美观风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "美观风格" },
                "运动风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/运动风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "运动风格" },
                "紧凑风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/紧凑风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "紧凑风格" },
                "宽敞风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/宽敞风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "宽敞风格" },
                "纯净风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/纯净风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "纯净风格" },
                "透明风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/透明风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "透明风格" },
                "地中海风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/地中海风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "地中海风格" },
                "个性风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/个性风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "个性风格" },
                "科技风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/科技风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "科技风格" },
                "线条风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/线条风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "线条风格" },
                "平滑风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/平滑风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "平滑风格" },
                "圆润风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/圆润风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "圆润风格" },
                "复合风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/复合风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "复合风格" },
                "纹理风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/纹理风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "纹理风格" },
                "隐藏式风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/隐藏式风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "隐藏式风格" },
                "可折叠风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可折叠风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可折叠风格" },
                "生态风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/生态风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "生态风格" },
                "浪漫风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/浪漫风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "浪漫风格" },
                "可重复利用风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可重复利用风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可重复利用风格" },
                "激进风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/激进风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "激进风格" },
                "革新风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/革新风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "革新风格" },
                "保暖风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/保暖风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "保暖风格" },
                "冷静风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/冷静风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "冷静风格" },
                "豪华风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/豪华风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "豪华风格" },
                "环形风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/环形风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "环形风格" },
                "时光风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/时光风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "时光风格" },
                "装饰性风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/装饰性风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "装饰性风格" },
                "内敛风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/内敛风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "内敛风格" },
                "明快风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/明快风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "明快风格" },
                "模块化风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/模块化风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "模块化风格" },
                "智能风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/智能风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "智能风格" },
                "多彩风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/多彩风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "多彩风格" },
                "通透风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/通透风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "通透风格" },
                "几何风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/几何风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "几何风格" },
                "异形风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/异形风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "异形风格" },
                "星空风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/星空风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "星空风格" },
                "大气风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/大气风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "大气风格" },
                "灵活风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/灵活风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "灵活风格" },
                "立方风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/立方风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "立方风格" },
                "木质风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/木质风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "木质风格" },
                "自由风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/自由风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "自由风格" },
                "融合风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/融合风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "融合风格" },
                "水晶风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/水晶风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "水晶风格" },
                "碎片风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/碎片风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "碎片风格" },
                "质感风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/质感风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "质感风格" },
                "可持续风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/可持续风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "可持续风格" },
                "镜面风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/镜面风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "镜面风格" },
                "未来风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/未来风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "未来风格" },
                "网状风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/网状风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "网状风格" },
                "空灵风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/空灵风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "空灵风格" },
                "灯光风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/灯光风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "灯光风格" },
                "美食风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/美食风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "美食风格" },
                "多功能风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/多功能风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "多功能风格" },
                "高度风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/高度风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "高度风格" },
                "传统风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/传统风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "传统风格" },
                "纤细风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/纤细风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "纤细风格" },
                "环绕风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/环绕风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "环绕风格" },
                "混搭风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/混搭风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "混搭风格" },
                "坚固风格": { icon: <img src={process.env.PUBLIC_URL + "/textures/产品风格/坚固风格.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "坚固风格" },
            },
            "环境背景": {
                "白色背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/白色背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "白色背景" },
                "黑色背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/黑色背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "黑色背景" },
                "简洁背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/简洁背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "简洁背景" },
                "反乌托邦背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/反乌托邦背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "反乌托邦背景" },
                "幻想背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/幻想背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "幻想背景" },
                "教室背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/教室背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "教室背景" },
                "异想天开背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/异想天开背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "异想天开背景" },
                "卧室背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/卧室背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "卧室背景" },
                "森林背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/森林背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "森林背景" },
                "废墟背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/废墟背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "废墟背景" },
                "城市背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/城市背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "城市背景" },
                "废弃城市建筑群背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/废弃城市建筑群背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "废弃城市建筑群背景" },
                "近未来都市背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/近未来都市背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "近未来都市背景" },
                "街景背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/街景背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "街景背景" },
                "炼金室背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/炼金室背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "炼金室背景" },
                "宇宙背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/宇宙背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "宇宙背景" },
                "雨天背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/雨天背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "雨天背景" },
                "在晨雾中背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/在晨雾中背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "在晨雾中背景" },
                "充满阳光背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/充满阳光背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "充满阳光背景" },
                "银河背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/银河背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "银河背景" },
                "黑暗地牢背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/黑暗地牢背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "黑暗地牢背景" },
                "星云背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/星云背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "星云背景" },
                "疯狂麦斯沙地风格背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/疯狂麦斯沙地风格背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "疯狂麦斯沙地风格背景" },
                "草原草地背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/草原草地背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "草原草地背景" },
                "杂草丛生背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/杂草丛生背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "杂草丛生背景" },
                "后启示录、末日后背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/后启示录、末日后背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "后启示录、末日后背景" },
                "极小空间背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/极小空间背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "极小空间背景" },
                "雾背景": { icon: <img src={process.env.PUBLIC_URL + "/textures/背景环境/雾背景.png"} style={{ width: "84px", height: "84px", backgroundColor: "#5f5f5f" }} alt="" />, name: "雾背景" },
            }
        },
        "屏蔽词": {
            "about": true,
            "across": true,
            "after": true,
            "against": true,
            "among": true,
            "around": true,
            "at": true,
            "before": true,
            "behind": true,
            "below": true,
            "beside": true,
            "but": true,
            "by": true,
            "down": true,
            "during": true,
            "for": true,
            "from": true,
            "in": true,
            "of": true,
            "on": true,
            "over": true,
            "near": true,
            "round": true,
            "since": true,
            "to": true,
            "under": true,
            "up": true,
            "with": true,
            "inside": true,
            "into": true,
            "outside": true,
            "throughout": true,
            "upon": true,
            "without": true,
            "within": true,
            "and": true,
            "or": true,
            "yet": true,
            "not": true,
            "nor": true,
            "neither": true,
        },
        "翻译": {
            "彩墨纸本风格": "color ink on paper Style",
            "涂鸦风格": "doodle Style",
            "伏尼契手稿风格": "Voynich manuscript Style",
            "东方山水画风格": "Tradition Chinese Ink Painting style Style",
            "浮世绘风格": "Japanese Ukiyo-e Style",
            "日本漫画风格": "Japanese comics/manga Style",
            "童话故事书插图风格": "Illustration Style of Fairy Tale Books Style",
            "梦工厂动画风格": "DreamWorks Animation Style",
            "梦工厂影业风格": "DreamWorks Pictures Style",
            "皮克斯风格": "Pixar Style",
            "时尚风格": "Fashion Style",
            "日本海报风格": "Japanese poster style Style",
            "90年代电视游戏90风格": "s video game Style",
            "法国艺术风格": "french art Style",
            "现代风格": "Modern Style",
            "经典风格": "Classic Style",
            "复古风格": "Vintage Style",
            "优雅风格": "Elegant Style",
            "奢华风格": "Luxurious Style",
            "实用风格": "Practical Style",
            "工业风格": "Industrial Style",
            "创意风格": "Creative Style",
            "温馨风格": "Cozy Style",
            "高科技风格": "High-tech Style",
            "环保风格": "Eco-friendly Style",
            "艺术风格": "Artistic Style",
            "手工风格": "Handmade Style",
            "乡村风格": "Rustic Style",
            "北欧风格": "Scandinavian Style",
            "极简风格": "Minimal Style",
            "立体风格": "Three-dimensional Style",
            "拉丁风格": "Latin Style",
            "迷你风格": "Mini Style",
            "动感风格": "Dynamic Style",
            "美式风格": "American Style",
            "异国风格": "Exotic Style",
            "舒适风格": "Comfortable Style",
            "轻奢风格": "Light-luxury Style",
            "阳光风格": "Sunny Style",
            "干净风格": "Clean Style",
            "趣味风格": "Playful Style",
            "自然风格": "Natural Style",
            "新奇风格": "Novel Style",
            "优质风格": "High-quality Style",
            "抽象风格": "Abstract Style",
            "家庭风格": "Homely Style",
            "独特风格": "Unique Style",
            "可爱风格": "Cute Style",
            "清新风格": "Refreshing Style",
            "精致风格": "Delicate Style",
            "粗犷风格": "Rugged Style",
            "老式风格": "Old-fashioned Style",
            "古典风格": "Classical Style",
            "活泼风格": "Lively Style",
            "金属风格": "Metallic Style",
            "幽默风格": "Humorous Style",
            "贴心风格": "Intimate Style",
            "可定制风格": "Customizable Style",
            "明亮风格": "Bright Style",
            "弧形风格": "Curved Style",
            "软性风格": "Soft Style",
            "强烈风格": "Intense Style",
            "可塑风格": "Moldable Style",
            "美观风格": "Aesthetic Style",
            "运动风格": "Sporty Style",
            "紧凑风格": "Compact Style",
            "宽敞风格": "Spacious Style",
            "纯净风格": "Pure Style",
            "透明风格": "Transparent Style",
            "地中海风格": "Mediterranean Style",
            "个性风格": "Personalized Style",
            "科技风格": "Tech-savvy Style",
            "线条风格": "Linear Style",
            "平滑风格": "Smooth Style",
            "圆润风格": "Rounded Style",
            "复合风格": "Composite Style",
            "纹理风格": "Textured Style",
            "隐藏式风格": "Hidden Style",
            "可折叠风格": "Foldable Style",
            "生态风格": "Ecological Style",
            "浪漫风格": "Romantic Style",
            "可重复利用风格": "Recyclable Style",
            "激进风格": "Radical Style",
            "革新风格": "Innovative Style",
            "保暖风格": "Warm Style",
            "冷静风格": "Cool Style",
            "豪华风格": "Opulent Style",
            "环形风格": "Circular Style",
            "时光风格": "Timeless Style",
            "装饰性风格": "Decorative Style",
            "内敛风格": "Subtle Style",
            "明快风格": "Vibrant Style",
            "模块化风格": "Modular Style",
            "智能风格": "Smart Style",
            "多彩风格": "Colorful Style",
            "通透风格": "Transparent Style",
            "几何风格": "Geometric Style",
            "异形风格": "Irregular Style",
            "星空风格": "Starry Style",
            "大气风格": "Atmospheric Style",
            "灵活风格": "Flexible Style",
            "立方风格": "Cubic Style",
            "木质风格": "Wooden Style",
            "自由风格": "Free Style",
            "融合风格": "Fusion Style",
            "羊毛风格": "Woolen Style",
            "水晶风格": "Crystal Style",
            "碎片风格": "Fragmented Style",
            "质感风格": "Textured Style",
            "皮革风格": "Leather Style",
            "可持续风格": "Sustainable Style",
            "竹质风格": "Bamboo Style",
            "石材风格": "Stone Style",
            "镜面风格": "Mirror Style",
            "未来风格": "Futuristic Style",
            "网状风格": "Mesh Style",
            "空灵风格": "Ethereal Style",
            "玻璃风格": "Glass Style",
            "灯光风格": "Illuminated Style",
            "美食风格": "Gourmet Style",
            "多功能风格": "Multifunctional Style",
            "高度风格": "Height Style",
            "传统风格": "Traditional Style",
            "纤细风格": "Slender Style",
            "环绕风格": "Surrounding Style",
            "混搭风格": "Mixed Style",
            "坚固风格": "Sturdy Style",
            "包豪斯风格": "Bauhaus Style",
            "简约风格": "Minimalist Style",
            "像素画风格": "Pixel Style",
            "未来主义风格": "futuristic Style",
            "极简主义风格": "Minimalist Style",
            "粗犷主义风格": "brutalist Style",
            "建构主义风格": "Constructivist Style",
            "旷野之息风格": "botw Style",
            "星际战甲风格": "Warframe Style",
            "达芬奇风格": "Leonardo Da Vinci Style",
            "漫画风格": "manga Style",
            "点彩派风格": "pointillism Style",
            "莫奈风格": "Claude Monet Style",
            "绗缝艺术风格": "quilted art Style",
            "简洁背景": "simple background",
            "反乌托邦背景": "dystopia,anti-utopia background",
            "幻想背景": "fantasy background",
            "教室背景": "classroom background",
            "异想天开背景": "whimsically background",
            "卧室背景": "bedroom background",
            "森林背景": "forest background",
            "废墟背景": "ruins background",
            "城市背景": "city background",
            "废弃城市建筑群背景": "deserted city buildings background",
            "近未来都市背景": "near future city background",
            "街景背景": "street scenery background",
            "炼金室背景": "Alchemy Laboratory background",
            "宇宙背景": "universe l cosmos background",
            "雨天背景": "rain background",
            "在晨雾中背景": "ln the morning mist background",
            "充满阳光背景": "full of sunlight background",
            "银河背景": "galaxy background",
            "黑暗地牢背景": "dungeon background",
            "星云背景": "nebula background",
            "疯狂麦斯沙地风格背景": "mad max background",
            "巴比伦空中花园背景": "Hanging Gardens of Babylon background",
            "草原草地背景": "meadow background",
            "杂草丛生背景": "overgrown nature background",
            "后启示录、末日后背景": "post apocalyptic background",
            "有机的，可生长背景": "growing, alive background",
            "极小空间背景": "liminal space background",
            "雾背景": "mist background",
            "天空之城背景": "Castle in the Sky background",
            "铅笔": "pen",
            "钢笔": "ink",
            "马克笔": "marker",
            "白色背景": "white background",
            "黑色背景": "black background",
            "简约": "Minimalist",
            "经典": "Classic",
            "复古": "Vintage",
            "时尚": "Stylish",
            "索尼": "Sony",
            "高科技": "High-tech",
            "巴洛克风格": "Baroque Style",
            "单个": "single",
            "1:1": "1:1",
            "2:1": "2:1",
            "1:2": "1:2",
            "低质量": "low quality",
            "中质量": "middle quality",
            "高质量": "high quality",
            "浅景深": "Close Shot",
            "中景深": "Medium Shot",
            "远景深": "Long Shot",
            "高风格化": "high stylize",
            "低风格化": "low stylize",
            "普通版": "normal version",
            "高级版": "advanced version",
            "多个随机": "multi random",
            "多个整齐": "multi order",
            "黑色": "black",
            "蓝色": "blue",
            "紫色": "purple",
            "灰色": "gray",
            "红色": "red",
            "绿色": "green",
            "黄色": "yellow",
            "V1": "V1",
            "V2": "V2",
            "V3": "V3",
            "V4": "V4",
            "V5": "V5",
            "混沌值": "chaos",
            "种子编号": "seed",
            "正视图": "front view",
            "俯视图": "side view",
            "侧视图": "rear view",
            "三视图": "three view",
            "棉材质": "Cotton Material",
            "涤纶材质": "Polyester Material",
            "丝绸材质": "Silk Material",
            "羊毛材质": "Wool Material",
            "腈纶材质": "Acrylic Material",
            "麻材质": "Linen Material",
            "竹纤维材质": "Bamboo fiber Material",
            "尼龙材质": "Nylon Material",
            "聚酯材质": "Polyethylene Material",
            "蕾丝材质": "Lace Material",
            "棉麻材质": "Cotton-linen Material",
            "氨纶材质": "Spandex Material",
            "混纺材质": "Blended fabric Material",
            "拉链材质": "Zipper Material",
            "皮革材质": "Leather Material",
            "仿皮材质": "Faux leather Material",
            "胶合板材质": "Plywood Material",
            "人造板材质": "Particleboard Material",
            "复合地板材质": "Laminate flooring Material",
            "实木地板材质": "Solid wood flooring Material",
            "陶瓷材质": "Ceramic Material",
            "马赛克材质": "Mosaic Material",
            "玻璃材质": "Glass Material",
            "金属材质": "Metal Material",
            "铁材质": "Iron Material",
            "钢材质": "Steel Material",
            "铝材质": "Aluminum Material",
            "铜材质": "Copper Material",
            "铅材质": "Lead Material",
            "镀锌钢材质": "Galvanized steel Material",
            "不锈钢材质": "Stainless steel Material",
            "铬材质": "Chrome Material",
            "镍材质": "Nickel Material",
            "纸张材质": "Paper Material",
            "塑料材质": "Plastic Material",
            "PVC材质": "PVC Material",
            "乳胶材质": "Latex Material",
            "硅胶材质": "Silicone Material",
            "橡胶材质": "Rubber Material",
            "泡沫材质": "Foam Material",
            "海绵材质": "Sponge Material",
            "木头材质": "Wood Material",
            "胶木材质": "Glulam Material",
            "橡木材质": "Oak Material",
            "桦木材质": "Birch Material",
            "枫木材质": "Maple Material",
            "樱桃木材质": "Cherry wood Material",
            "黄杨木材质": "Boxwood Material",
            "竹子材质": "Bamboo Material",
            "水泥材质": "Cement Material",
            "石膏材质": "Gypsum Material",
            "砖材质": "Brick Material",
            "石头材质": "Stone Material",
            "大理石材质": "Marble Material",
            "花岗岩材质": "Granite Material",
            "玄武岩材质": "Basalt Material",
            "石英材质": "Quartz Material",
            "玻璃纤维材质": "Fiberglass Material",
            "碳纤维材质": "Carbon fiber Material",
            "石棉材质": "Asbestos Material",
            "矿棉材质": "Mineral wool Material",
            "草编材质": "Straw weaving Material",
            "藤编材质": "Rattan weaving Material",
            "竹编材质": "Bamboo weaving Material",
            "棉线材质": "Cotton thread Material",
            "麻线材质": "Hemp thread Material",
            "编织物材质": "Woven fabric Material",
            "针织物材质": "Knitted fabric Material",
            "羽绒材质": "Down Material",
            "珍珠棉材质": "Pearl cotton Material",
            "三明治布材质": "Sandwich fabric Material",
            "软陶材质": "Soft pottery Material",
            "聚氨酯材质": "Polyurethane Material",
            "羊绒材质": "Cashmere Material",
            "麂皮材质": "Suede Material",
            "亚克力材质": "Acrylic Material",
            "镁合金材质": "Magnesium alloy Material",
            "钛合金材质": "Titanium alloy Material",
            "锌合金材质": "Zinc alloy Material",
            "硅酸盐材质": "Silicate Material",
            "酒瓶绿材质": "Bottle green Material",
            "硝基棉材质": "Nitrocellulose Material",
            "硫化纤维材质": "Sulfide fiber Material",
            "醋酸纤维材质": "Acetate fiber Material",
            "玉石材质": "Jade Material",
            "珊瑚材质": "Coral Material",
            "贝壳材质": "Shell Material",
            "水晶材质": "Crystal Material",
            "琉璃材质": "Colored glaze Material",
            "镁板材质": "Magnesium plate Material",
            "铁皮材质": "Tinplate Material",
            "棕榈叶材质": "Palm leaf Material",
            "软木材质": "Cork Material",
            "泡材质": "Foam Material",
            "麦穗材质": "Wheat straw Material",
            "玉米皮材质": "Corn husk Material",
            "麻布材质": "Burlap Material",
            "羊毛毡材质": "Wool felt Material",
            "皮革带材质": "Leather belt Material",
            "棉纱材质": "Cotton yarn Material",
            "油布材质": "Oilcloth Material",
            "镀金属材质": "Gold plating Material",
            "镀银材质": "Silver plating Material",
            "镀铜材质": "Copper plating Material",
            "镀铝材质": "Aluminum plating Material",
            "镀锌材质": "Zinc plating Material",
            "镀锡材质": "Tin plating Material",
            "镀镍材质": "Nickel plating Material",
            "镀铬材质": "Chrome plating Material",
            "砂纸材质": "Sandpaper Material",
            "砂布材质": "Emery cloth Material",
            "砂轮材质": "Grinding wheel Material",
            "纱线材质": "Yarn Material",
            "粘合剂材质": "Adhesive Material",
            "隔热材料材质": "Insulation material Material",
            "网布材质": "Mesh fabric Material",
            "帆布材质": "Canvas Material",
            "蜡烛材质": "Candle Material",
            "泥土材质": "Clay Material",
            "沙子材质": "Sand Material",
            "泥炭材质": "Peat Material",
            "花岗岩碎石材质": "Granite gravel Material",
            "卵石材质": "Pebble Material",
            "索尼风格": "Sony Style",
            "克劳德莫奈风格": "Claude Monet Style",
            "局部解剖风格": "Partial Anatomy Style",
            "90年代电视游戏风格": "90s Video Game Style",
            "PE材质": "Polyethylene Material",
            "PP材质": "Polypropylene Material",
            "ABS材质": "Acrylonitrile Butadiene Styrene Material",
            "PC材质": "Polycarbonate Material",
        },
        "表达式": {
            "棉材质": "Cotton Material",
            "涤纶材质": "Polyester Material",
            "丝绸材质": "Silk Material",
            "羊毛材质": "Wool Material",
            "腈纶材质": "Acrylic Material",
            "麻材质": "Linen Material",
            "竹纤维材质": "Bamboo fiber Material",
            "尼龙材质": "Nylon Material",
            "聚酯材质": "Polyethylene Material",
            "蕾丝材质": "Lace Material",
            "棉麻材质": "Cotton-linen Material",
            "氨纶材质": "Spandex Material",
            "混纺材质": "Blended fabric Material",
            "拉链材质": "Zipper Material",
            "皮革材质": "Leather Material",
            "仿皮材质": "Faux leather Material",
            "胶合板材质": "Plywood Material",
            "人造板材质": "Particleboard Material",
            "复合地板材质": "Laminate flooring Material",
            "实木地板材质": "Solid wood flooring Material",
            "陶瓷材质": "Ceramic Material",
            "马赛克材质": "Mosaic Material",
            "玻璃材质": "Glass Material",
            "金属材质": "Metal Material",
            "铁材质": "Iron Material",
            "钢材质": "Steel Material",
            "铝材质": "Aluminum Material",
            "铜材质": "Copper Material",
            "铅材质": "Lead Material",
            "镀锌钢材质": "Galvanized steel Material",
            "不锈钢材质": "Stainless steel Material",
            "铬材质": "Chrome Material",
            "镍材质": "Nickel Material",
            "纸张材质": "Paper Material",
            "塑料材质": "Plastic Material",
            "PVC材质": "PVC Material",
            "乳胶材质": "Latex Material",
            "硅胶材质": "Silicone Material",
            "橡胶材质": "Rubber Material",
            "泡沫材质": "Foam Material",
            "海绵材质": "Sponge Material",
            "木头材质": "Wood Material",
            "胶木材质": "Glulam Material",
            "橡木材质": "Oak Material",
            "桦木材质": "Birch Material",
            "枫木材质": "Maple Material",
            "樱桃木材质": "Cherry wood Material",
            "黄杨木材质": "Boxwood Material",
            "竹子材质": "Bamboo Material",
            "水泥材质": "Cement Material",
            "石膏材质": "Gypsum Material",
            "砖材质": "Brick Material",
            "石头材质": "Stone Material",
            "大理石材质": "Marble Material",
            "花岗岩材质": "Granite Material",
            "玄武岩材质": "Basalt Material",
            "石英材质": "Quartz Material",
            "玻璃纤维材质": "Fiberglass Material",
            "碳纤维材质": "Carbon fiber Material",
            "石棉材质": "Asbestos Material",
            "矿棉材质": "Mineral wool Material",
            "草编材质": "Straw weaving Material",
            "藤编材质": "Rattan weaving Material",
            "竹编材质": "Bamboo weaving Material",
            "棉线材质": "Cotton thread Material",
            "麻线材质": "Hemp thread Material",
            "编织物材质": "Woven fabric Material",
            "针织物材质": "Knitted fabric Material",
            "羽绒材质": "Down Material",
            "珍珠棉材质": "Pearl cotton Material",
            "三明治布材质": "Sandwich fabric Material",
            "软陶材质": "Soft pottery Material",
            "聚氨酯材质": "Polyurethane Material",
            "羊绒材质": "Cashmere Material",
            "麂皮材质": "Suede Material",
            "亚克力材质": "Acrylic Material",
            "镁合金材质": "Magnesium alloy Material",
            "钛合金材质": "Titanium alloy Material",
            "锌合金材质": "Zinc alloy Material",
            "硅酸盐材质": "Silicate Material",
            "酒瓶绿材质": "Bottle green Material",
            "硝基棉材质": "Nitrocellulose Material",
            "硫化纤维材质": "Sulfide fiber Material",
            "醋酸纤维材质": "Acetate fiber Material",
            "玉石材质": "Jade Material",
            "珊瑚材质": "Coral Material",
            "贝壳材质": "Shell Material",
            "水晶材质": "Crystal Material",
            "琉璃材质": "Colored glaze Material",
            "镁板材质": "Magnesium plate Material",
            "铁皮材质": "Tinplate Material",
            "棕榈叶材质": "Palm leaf Material",
            "软木材质": "Cork Material",
            "泡材质": "Foam Material",
            "麦穗材质": "Wheat straw Material",
            "玉米皮材质": "Corn husk Material",
            "麻布材质": "Burlap Material",
            "羊毛毡材质": "Wool felt Material",
            "皮革带材质": "Leather belt Material",
            "棉纱材质": "Cotton yarn Material",
            "油布材质": "Oilcloth Material",
            "镀金属材质": "Gold plating Material",
            "镀银材质": "Silver plating Material",
            "镀铜材质": "Copper plating Material",
            "镀铝材质": "Aluminum plating Material",
            "镀锌材质": "Zinc plating Material",
            "镀锡材质": "Tin plating Material",
            "镀镍材质": "Nickel plating Material",
            "镀铬材质": "Chrome plating Material",
            "砂纸材质": "Sandpaper Material",
            "砂布材质": "Emery cloth Material",
            "砂轮材质": "Grinding wheel Material",
            "纱线材质": "Yarn Material",
            "粘合剂材质": "Adhesive Material",
            "隔热材料材质": "Insulation material Material",
            "网布材质": "Mesh fabric Material",
            "帆布材质": "Canvas Material",
            "蜡烛材质": "Candle Material",
            "泥土材质": "Clay Material",
            "沙子材质": "Sand Material",
            "泥炭材质": "Peat Material",
            "花岗岩碎石材质": "Granite gravel Material",
            "卵石材质": "Pebble Material",
            "正视图": "front view",
            "俯视图": "side view",
            "侧视图": "rear view",
            "三视图": "three view",
            "彩墨纸本风格": "color ink on paper Style",
            "涂鸦风格": "doodle Style",
            "伏尼契手稿风格": "Voynich manuscript Style",
            "东方山水画风格": "Tradition Chinese Ink Painting style Style",
            "浮世绘风格": "Japanese Ukiyo-e Style",
            "日本漫画风格": "Japanese comics/manga Style",
            "童话故事书插图风格": "Illustration Style of Fairy Tale Books Style",
            "梦工厂动画风格": "DreamWorks Animation Style",
            "梦工厂影业风格": "DreamWorks Pictures Style",
            "皮克斯风格": "Pixar Style",
            "时尚风格": "Fashion Style",
            "日本海报风格": "Japanese poster style Style",
            "90年代电视游戏90风格": "s video game Style",
            "法国艺术风格": "french art Style",
            "现代风格": "Modern Style",
            "经典风格": "Classic Style",
            "复古风格": "Vintage Style",
            "优雅风格": "Elegant Style",
            "奢华风格": "Luxurious Style",
            "实用风格": "Practical Style",
            "工业风格": "Industrial Style",
            "创意风格": "Creative Style",
            "温馨风格": "Cozy Style",
            "高科技风格": "High-tech Style",
            "环保风格": "Eco-friendly Style",
            "艺术风格": "Artistic Style",
            "手工风格": "Handmade Style",
            "乡村风格": "Rustic Style",
            "北欧风格": "Scandinavian Style",
            "极简风格": "Minimal Style",
            "立体风格": "Three-dimensional Style",
            "拉丁风格": "Latin Style",
            "迷你风格": "Mini Style",
            "动感风格": "Dynamic Style",
            "美式风格": "American Style",
            "异国风格": "Exotic Style",
            "舒适风格": "Comfortable Style",
            "轻奢风格": "Light-luxury Style",
            "阳光风格": "Sunny Style",
            "干净风格": "Clean Style",
            "趣味风格": "Playful Style",
            "自然风格": "Natural Style",
            "新奇风格": "Novel Style",
            "优质风格": "High-quality Style",
            "抽象风格": "Abstract Style",
            "家庭风格": "Homely Style",
            "独特风格": "Unique Style",
            "可爱风格": "Cute Style",
            "清新风格": "Refreshing Style",
            "精致风格": "Delicate Style",
            "粗犷风格": "Rugged Style",
            "老式风格": "Old-fashioned Style",
            "古典风格": "Classical Style",
            "活泼风格": "Lively Style",
            "金属风格": "Metallic Style",
            "幽默风格": "Humorous Style",
            "贴心风格": "Intimate Style",
            "可定制风格": "Customizable Style",
            "明亮风格": "Bright Style",
            "弧形风格": "Curved Style",
            "软性风格": "Soft Style",
            "强烈风格": "Intense Style",
            "可塑风格": "Moldable Style",
            "美观风格": "Aesthetic Style",
            "运动风格": "Sporty Style",
            "紧凑风格": "Compact Style",
            "宽敞风格": "Spacious Style",
            "纯净风格": "Pure Style",
            "透明风格": "Transparent Style",
            "地中海风格": "Mediterranean Style",
            "个性风格": "Personalized Style",
            "科技风格": "Tech-savvy Style",
            "线条风格": "Linear Style",
            "平滑风格": "Smooth Style",
            "圆润风格": "Rounded Style",
            "复合风格": "Composite Style",
            "纹理风格": "Textured Style",
            "隐藏式风格": "Hidden Style",
            "可折叠风格": "Foldable Style",
            "生态风格": "Ecological Style",
            "浪漫风格": "Romantic Style",
            "可重复利用风格": "Recyclable Style",
            "激进风格": "Radical Style",
            "革新风格": "Innovative Style",
            "保暖风格": "Warm Style",
            "冷静风格": "Cool Style",
            "豪华风格": "Opulent Style",
            "环形风格": "Circular Style",
            "时光风格": "Timeless Style",
            "装饰性风格": "Decorative Style",
            "内敛风格": "Subtle Style",
            "明快风格": "Vibrant Style",
            "模块化风格": "Modular Style",
            "智能风格": "Smart Style",
            "多彩风格": "Colorful Style",
            "通透风格": "Transparent Style",
            "几何风格": "Geometric Style",
            "异形风格": "Irregular Style",
            "星空风格": "Starry Style",
            "大气风格": "Atmospheric Style",
            "灵活风格": "Flexible Style",
            "立方风格": "Cubic Style",
            "木质风格": "Wooden Style",
            "自由风格": "Free Style",
            "融合风格": "Fusion Style",
            "羊毛风格": "Woolen Style",
            "水晶风格": "Crystal Style",
            "碎片风格": "Fragmented Style",
            "质感风格": "Textured Style",
            "皮革风格": "Leather Style",
            "可持续风格": "Sustainable Style",
            "竹质风格": "Bamboo Style",
            "石材风格": "Stone Style",
            "镜面风格": "Mirror Style",
            "未来风格": "Futuristic Style",
            "网状风格": "Mesh Style",
            "空灵风格": "Ethereal Style",
            "玻璃风格": "Glass Style",
            "灯光风格": "Illuminated Style",
            "美食风格": "Gourmet Style",
            "多功能风格": "Multifunctional Style",
            "高度风格": "Height Style",
            "传统风格": "Traditional Style",
            "纤细风格": "Slender Style",
            "环绕风格": "Surrounding Style",
            "混搭风格": "Mixed Style",
            "坚固风格": "Sturdy Style",
            "包豪斯风格": "Bauhaus Style",
            "简约风格": "Minimalist Style",
            "像素画风格": "Pixel Style",
            "未来主义风格": "futuristic Style",
            "极简主义风格": "Minimalist Style",
            "粗犷主义风格": "brutalist Style",
            "建构主义风格": "Constructivist Style",
            "旷野之息风格": "botw Style",
            "星际战甲风格": "Warframe Style",
            "达芬奇风格": "Leonardo Da Vinci Style",
            "漫画风格": "manga Style",
            "点彩派风格": "pointillism Style",
            "莫奈风格": "Claude Monet Style",
            "绗缝艺术风格": "quilted art Style",
            "简洁背景": "simple background",
            "反乌托邦背景": "dystopia,anti-utopia background",
            "幻想背景": "fantasy background",
            "教室背景": "classroom background",
            "异想天开背景": "whimsically background",
            "卧室背景": "bedroom background",
            "森林背景": "forest background",
            "废墟背景": "ruins background",
            "城市背景": "city background",
            "废弃城市建筑群背景": "deserted city buildings background",
            "近未来都市背景": "near future city background",
            "街景背景": "street scenery background",
            "炼金室背景": "Alchemy Laboratory background",
            "宇宙背景": "universe l cosmos background",
            "雨天背景": "rain background",
            "在晨雾中背景": "ln the morning mist background",
            "充满阳光背景": "full of sunlight background",
            "银河背景": "galaxy background",
            "黑暗地牢背景": "dungeon background",
            "星云背景": "nebula background",
            "疯狂麦斯沙地风格背景": "mad max background",
            "巴比伦空中花园背景": "Hanging Gardens of Babylon background",
            "草原草地背景": "meadow background",
            "杂草丛生背景": "overgrown nature background",
            "后启示录、末日后背景": "post apocalyptic background",
            "有机的，可生长背景": "growing, alive background",
            "极小空间背景": "liminal space background",
            "雾背景": "mist background",
            "天空之城背景": "Castle in the Sky background",
            "铅笔": "pencil",
            "钢笔": "pen",
            "马克笔": "industrial design color sketching",
            "白色背景": "white background",
            "黑色背景": "black background",
            "单个": "single",
            "多个随机": "many random",
            "多个整齐": "multiple neat",
            "简约": "Minimalist",
            "经典": "Classic",
            "复古": "Vintage",
            "索尼": "Sony",
            "时尚": "Stylish",
            "高科技": "High-tech",
            "巴洛克风格": "Baroque",
            "1:1": "::1 --ar 1:1",
            "2:1": "::1 --ar 2:1",
            "1:2": "::1 --ar 1:2",
            "低质量": "--q .25",
            "中质量": "--q 1",
            "高质量": "--q 5",
            "浅景深": "Close Shot",
            "中景深": "Medium Shot",
            "远景深": "Long Shot",
            "高风格化": "--stylize 1000",
            "中风格化": "--stylize 100",
            "低风格化": "--stylize 0",
            "黑色": "black",
            "蓝色": "blue",
            "紫色": "purple",
            "灰色": "grey",
            "红色": "red",
            "绿色": "green",
            "黄色": "yellow",
            "V1": "--v 5",
            "V2": "--v 4",
            "V3": "--v 3",
            "V4": "--v 2",
            "V5": "--v 1",
            "混沌值": "--c",
            "种子编号": "--seed",
            "索尼风格": "Sony Style",
            "克劳德莫奈风格": "Claude Monet Style",
            "90年代电视游戏风格": "90s Video Game Style",
            "PE材质": "Polyethylene Material",
            "PP材质": "Polypropylene Material",
            "ABS材质": "Acrylonitrile Butadiene Styrene Material",
            "PC材质": "Polycarbonate Material",
        },
    }
}